# Generated by Django 5.0.2 on 2024-02-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_remove_superadmin_user_delete_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('matricule', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=255, null=True)),
                ('type_piece', models.CharField(blank=True, max_length=255, null=True)),
                ('date_livrance', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_naissance', models.CharField(blank=True, max_length=10, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaireModifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.beneficiaire')),
            ],
        ),
    ]
